#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
command=$1
shift

case ${command} in
"tests")
  echo "running tests..."
  sleep 2
  echo "all tests passed!"
  ;;

"schema")
  echo "generating schema..."
  ./repo-1/scripts/generate-schema.sh
  ;;

"clone-repo-2")
  echo "cloning repo-2..."
  rm -rf repo-1/.temp
  mkdir repo-1/.temp
  cd repo-1/.temp
  git clone git@github.com:margostino/multiplex-request.git
  echo "verifying folder..."
  ls -la
  pwd
  echo "repo-2 cloned!"
  ;;

"update-schema")
  mv repo-1/schema.json repo-1/.temp/multiplex-request/repo-2/schema.json
  cd repo-1/.temp/multiplex-request/repo-2/schema.json
  ls -la
  echo "schema updated!"
  ;;

"build")
    echo "building app..."
    sleep 2
    echo "build done!"
  ;;

*)
  echo 'Invalid command'
  exit 1
  ;;
esac
