#!/bin/bash

SCRIPT_PATH="$(
  cd "$(dirname "$0")" >/dev/null 2>&1
  pwd -P
)"
command=$1
shift

case ${command} in
"tests")
  echo "running tests..."
  sleep 2
  echo "all tests passed!"
  ;;

"schema")
  echo "generating schema..."
  ./repo-1/scripts/generate-schema.sh
  ;;

"clone")
  echo "cloning repo-2..."
  export GIT_BRANCH_REPO_1=$(git rev-parse --abbrev-ref HEAD)
  mkdir /home/runner/work/.temp
  cd /home/runner/work/.temp
  git clone git@github.com:margostino/multiplex-request.git
  cd multiplex-request
  git checkout master

  export GIT_BRANCH_REPO_2=${GIT_BRANCH_REPO_1/r1/r2}

  BRANCH_EXIST_IN_REPO_2=$(git checkout ${GIT_BRANCH_REPO_2} 2>&1)
  echo "exist? ${BRANCH_EXIST_IN_REPO_2}"
  if [[ ${BRANCH_EXIST_IN_REPO_2} == "error"* ]]; then
    echo "branch ${GIT_BRANCH_REPO_2} does not exist in repo-2"
    git checkout -b ${GIT_BRANCH_REPO_2}
    echo "branch created"
    echo "trigger_pull_request=${GIT_BRANCH_REPO_2}" >> "$GITHUB_OUTPUT"
  else
    echo "branch ${GIT_BRANCH_REPO_2} already exists in repo-2"
    git checkout ${GIT_BRANCH_REPO_2}
    echo "trigger_pull_request=''" >> "$GITHUB_OUTPUT"
  fi

  echo "repo-2 cloned!"
  ;;

"update-schema")
  echo "updating schema..."
  git config --global user.email "multiplex-worker@margostino.com"
  git config --global user.name "multiplex-worker"
  cd /home/runner/work/.temp/multiplex-request
  mv /home/runner/work/multiplex-request/multiplex-request/repo-1/schema.json /home/runner/work/.temp/multiplex-request/schema.json
  git add .
  git commit -m "update schema"
  export GIT_BRANCH_REPO_2=$(git rev-parse --abbrev-ref HEAD)
  git push --set-upstream origin $GIT_BRANCH_REPO_2
  echo "schema updated!"
  ;;

"create-pull-request")
  echo "creating pull request..."
  git config --global user.email "multiplex-worker@margostino.com"
  git config --global user.name "multiplex-worker"
  cd /home/runner/work/.temp/multiplex-request
  export GIT_BRANCH_REPO_2=$(git rev-parse --abbrev-ref HEAD)

  curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${PR_TOKEN}"\
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/repos/margostino/multiplex-request/pulls \
    -d '{"title":"update schema","body":"Schema updated by Metadata","head":"${GIT_BRANCH_REPO_2}","base":"master"}'

  echo "pull request created!"
  ;;

"build")
  echo "building app..."
  sleep 2
  echo "build done!"
  ;;

*)
  echo 'Invalid command'
  exit 1
  ;;
esac
