# This is a basic workflow to help you get started with Actions

name: multiplex pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  push:
    branches:
      - 'id-r1-*'
#  pull_request:
#    branches:
#      - 'id-r1-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      trigger_pull_request: ${{ steps.check.outputs.trigger_pull_request }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: run tests REPO-1
        run: |
          whoami
          chmod +x ./repo-1/run
          ./repo-1/run tests
        shell: bash

  generate_schema:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: generate schema
        run: ./repo-1/run schema
        shell: bash

  clone_and_update_schema:
    runs-on: ubuntu-latest
    needs: generate_schema
    outputs:
      trigger_pull_request: ${{ steps.check.outputs.trigger_pull_request }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: clone & update schema (repo-2)
        id: check
        run: |
          ./repo-1/run clone
          ./repo-1/run update-schema
        shell: bash

      - name: create pull request (repo-2)
        run: ./repo-1/run create-pull-request
        shell: bash
        env:
          PR_TOKEN: ${{ secrets.PR_TOKEN }}

  pull_request:
    runs-on: ubuntu-latest
    needs: clone_and_update_schema
    if: needs.clone_and_update_schema.outputs.trigger_pull_request != ''
    steps:
      - uses: actions/checkout@v3

      - name: create pull request (repo-2)
        run: ./repo-1/run create-pull-request
        shell: bash
        env:
          PR_TOKEN: ${{ secrets.PR_TOKEN }}

#  multiplex-request:
#    runs-on: ubuntu-latest
#    needs: build
#    if: needs.build.outputs.trigger_pull_request != ''
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: create Pull Request in repo-2
#        uses: peter-evans/create-pull-request@v5.0.1
#        with:
#          commit-message: update schema
#          title: Update schema
#          body: Schema updated by Metadata
#          token: ${{ secrets.PR_TOKEN }}
#          base: master
#          branch: '${{ needs.build.outputs.trigger_pull_request }}'
